### ISSUE TITLE
CTRL-SHIFT-D conflicts with atom core keybinding

### ISSUE THREAD

**Issue by joncamfield** [jpohjolainen/atom-gpg#3]
The Atom Core plugin defines CTRL-SHIFT-D as "Duplicate" (editor:duplicate-lines) and this behavior overrides the atom-gpg command to decrypt.

Even after re-mapping decryption to a different, unconflicted key sequence, however, it is not triggering the action (though Packages->atom-gpg->Decrypt works as expected).  This is possible user error and I will continue to explore.

**Comment by jpohjolainen** [comment]
On what operating system you're using Atom? On my Mac the duplicate lines is CTRL-CMD-D.

**Comment by joncamfield** [comment]
Ubuntu Linux, 14.04 LTS; 3.13.0-76-generic

**Comment by mdrmike** [comment]
Mac CMD ≈ CTRL on gnu/linux & Windows.  Here's a [cheat sheet. The editing section](https://github.com/nwinkler/atom-keyboard-shortcuts#editing) confirms this is a core keystroke on both Windows & GNU/Linux.

**Comment by jpohjolainen** [comment]
Remapping works for me. Just tested and remapped encryption to cmd-shift-e and didn't even need to restart Atom or anything. 
What keymaps would you recommend? I'm using shift-alt-e and -d on my Hiera-Eyaml plugin and wouldn't want to overlap with those.

**Comment by mdrmike** [comment]
@messis-rocket I'm not sure why this issue was closed without a resolution?  Isn't the goal for this plugin to work for everyone by default?  The plugin doesn't work for any windows/linux users by default.  Asking all those users to remap keys doesn't seem to be a very nice solution. :frowning_face: 

I recommend it defaults to **`shift-alt-e`** and **`shift-alt-d`** which isn't used by Atom core.  

I get this keybinding conflicts with another plugin, but it works with Atom by default. As @jpohjolainen points out, remapping also works in this case. Also, seems likely that a plugin conflict is a much smaller use-case than all Windows and Linux users not being able to use atom-gpg plugin by default.

**Comment by messis-fin** [comment]
Ok. I will change the keystroke to alt-shift-[e/d/s] on next release.

**Comment by messis-fin** [comment]
New version released with alt-shift- keymapping. Closing the issue.
